version: '2'

networks:
  webnet:
  db_network:

volumes:
  postgres_data:

services:
  backend:
    restart: on-failure
    build: .
    env_file: .env
    command: uwsgi --socket=:8002 --module=project.wsgi:application --py-autoreload=1
    volumes:
      - .:/app
      - ./static:/app/static
    depends_on:
      - database
    networks:
      - webnet
      - db_network
    links:
      - database:database

  database:
    image: kartoza/postgis:12.0
    volumes:
      - ./docker/postgres:/var/lib/postgresql/12/main
      - dbbackups:/backups
    env_file: .env
    expose:
      - '5433'
    ports:
      - '5433:5432'
    restart: on-failure
    networks:
      - db_network

  nginx:
    image: nginx:1.15.0
    depends_on:
      - websockets
      - backend
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/app/static
    networks:
      - webnet
    ports:
      - '4000:80'

